last_change = 2026-09-29T14:51:39.564746Z
addr = 0x24950
size = 0x515
name = "CDemoRecorder_WriteSpawnGroups"
type = "char"

[header]
name = "CDemoRecorder_WriteSpawnGroups"
addr = 0x24950
type = "char"

[header.args]
