last_change = 2026-09-29T14:51:37.549315Z
addr = 0x370d0
size = 0x16e
name = "Demo_PauseAtServerTick_CommandHandler"
type = "double"

[header]
name = "Demo_PauseAtServerTick_CommandHandler"
addr = 0x370d0
type = "double"

[header.args]
