last_change = 2026-09-29T14:51:39.661661Z
addr = 0x454f0
size = 0x50d
name = "CNetworkGameClient_CopyNewEntity"
type = "long long"

[header]
name = "CNetworkGameClient_CopyNewEntity"
addr = 0x454f0
type = "long long"

[header.args]
