last_change = 2026-09-29T14:51:39.696495Z
addr = 0x45ec0
size = 0x1fb
name = "CNetworkGameClient_RecordEntityBandwidth"
type = "void"

[header]
name = "CNetworkGameClient_RecordEntityBandwidth"
addr = 0x45ec0
type = "void"

[header.args]
