last_change = 2026-09-29T14:51:39.696609Z
addr = 0x46960
size = 0xa9f
name = "CNetworkGameClient_ProcessPacketEntitiesInternal"
type = "char"

[header]
name = "CNetworkGameClient_ProcessPacketEntitiesInternal"
addr = 0x46960
type = "char"

[header.args]
