last_change = 2026-09-29T14:51:39.679094Z
addr = 0x45d50
size = 0x16b
name = "CNetworkGameClient_OnPreserveEntity"
type = "long long"

[header]
name = "CNetworkGameClient_OnPreserveEntity"
addr = 0x45d50
type = "long long"

[header.args]
