last_change = 2026-09-29T14:51:39.749007Z
addr = 0x5c770
size = 0x489
name = "CNetworkClientSpawnGroupCreatePrerequisites_GetStatus"
type = "long long"

[header]
name = "CNetworkClientSpawnGroupCreatePrerequisites_GetStatus"
addr = 0x5c770
type = "long long"

[header.args]
