last_change = 2026-09-29T14:51:39.722537Z
addr = 0x56620
size = 0x2ba
name = "ConnectSocketToAddressList"
type = "long long"

[header]
name = "ConnectSocketToAddressList"
addr = 0x56620
type = "long long"

[header.args]
