last_change = 2026-09-29T14:51:37.549352Z
addr = 0x5fbc0
size = 0x86
name = "Callback_GenericChanged"
type = "void"

[header]
name = "Callback_GenericChanged"
addr = 0x5fbc0
type = "void"

[header.args]
