last_change = 2026-09-29T14:51:37.549350Z
addr = 0x5fae0
size = 0xda
name = "CNetworkGameClient_HookClientStringTable"
type = "long long"

[header]
name = "CNetworkGameClient_HookClientStringTable"
addr = 0x5fae0
type = "long long"

[header.args]
