last_change = 2026-09-29T14:51:39.749179Z
addr = 0x5f310
size = 0x7c4
name = "CNetworkGameClient_SetSignonState"
type = "char"

[header]
name = "CNetworkGameClient_SetSignonState"
addr = 0x5f310
type = "char"

[header.args]
