last_change = 2026-09-29T14:51:39.801285Z
addr = 0x62f30
size = 0x1e4
name = "CNetworkGameClient_CreateMove"
type = "void"

[header]
name = "CNetworkGameClient_CreateMove"
addr = 0x62f30
type = "void"

[header.args]
