last_change = 2026-09-29T14:51:37.549384Z
addr = 0x6d390
size = 0x19a
name = "CNetworkGameClient_PrintNetStats"
type = "void"

[header]
name = "CNetworkGameClient_PrintNetStats"
addr = 0x6d390
type = "void"

[header.args]
