last_change = 2026-09-29T14:51:39.853638Z
addr = 0x67840
size = 0x479
name = "CNetworkGameClient_DisconnectGame"
type = "long long"

[header]
name = "CNetworkGameClient_DisconnectGame"
addr = 0x67840
type = "long long"

[header.args]
