last_change = 2026-09-29T14:51:37.549357Z
addr = 0x600c0
size = 0x1a9
name = "CNetworkGameClient_Clear"
type = "void"

[header]
name = "CNetworkGameClient_Clear"
addr = 0x600c0
type = "void"

[header.args]
