last_change = 2026-09-29T14:51:37.549359Z
addr = 0x60270
size = 0x1ee
name = "CNetworkGameClient_FullConnect"
type = "double"

[header]
name = "CNetworkGameClient_FullConnect"
addr = 0x60270
type = "double"

[header.args]
