last_change = 2026-09-29T14:51:37.549373Z
addr = 0x680e0
size = 0xbe7
name = "CNetworkGameClientBase_ClockDrift_AdjustFrameTime"
type = "__m128"

[header]
name = "CNetworkGameClientBase_ClockDrift_AdjustFrameTime"
addr = 0x680e0
type = "__m128"

[header.args]
