last_change = 2026-09-29T14:51:37.549376Z
addr = 0x69280
size = 0x16b
name = "CNetworkGameClient_ProcessServerInfo"
type = "char"

[header]
name = "CNetworkGameClient_ProcessServerInfo"
addr = 0x69280
type = "char"

[header.args]
