last_change = 2026-09-29T14:51:39.818751Z
addr = 0x632d0
size = 0x744
name = "CNetworkGameClient_SendMovePacket"
type = "char"

[header]
name = "CNetworkGameClient_SendMovePacket"
addr = 0x632d0
type = "char"

[header.args]
