last_change = 2026-09-29T14:51:37.549365Z
addr = 0x63ae0
size = 0x3a3
name = "CNetworkGameClient_SendMove"
type = "void"

[header]
name = "CNetworkGameClient_SendMove"
addr = 0x63ae0
type = "void"

[header.args]
