last_change = 2026-09-29T14:51:37.549393Z
addr = 0x744f0
size = 0x8
name = "CEngineServer_GetFrameTimeAmnesty"
type = "const char *"

[header]
name = "CEngineServer_GetFrameTimeAmnesty"
addr = 0x744f0
type = "const char *"

[header.args]
