last_change = 2026-09-29T14:51:37.549416Z
addr = 0x7ddd0
size = 0x177
name = "CNetworkGameClientBase_Connect"
type = "void"

[header]
name = "CNetworkGameClientBase_Connect"
addr = 0x7ddd0
type = "void"

[header.args]
