last_change = 2026-09-29T14:51:37.549401Z
addr = 0x748a0
size = 0x24
name = "CEngineClient_ExecuteClientCmd"
type = "long long"

[header]
name = "CEngineClient_ExecuteClientCmd"
addr = 0x748a0
type = "long long"

[header.args]
