last_change = 2026-09-29T14:51:37.549407Z
addr = 0x74eb0
size = 0x27
name = "CEngineClient_GetEntityLumpForTemplate"
type = "long long"

[header]
name = "CEngineClient_GetEntityLumpForTemplate"
addr = 0x74eb0
type = "long long"

[header.args]
