last_change = 2026-09-29T14:51:37.549388Z
addr = 0x728a0
size = 0xb4
name = "CEngineServer_GetSteamUniverse"
type = "long long"

[header]
name = "CEngineServer_GetSteamUniverse"
addr = 0x728a0
type = "long long"

[header.args]
