last_change = 2026-09-29T14:51:37.549414Z
addr = 0x75510
size = 0x8
name = "CEngineServer_GetAchievementMgr"
type = "long long"

[header]
name = "CEngineServer_GetAchievementMgr"
addr = 0x75510
type = "long long"

[header.args]
