last_change = 2026-09-29T14:51:37.549409Z
addr = 0x74ee0
size = 0x7
name = "CEngineClient_GetStatsAppID"
type = "long long"

[header]
name = "CEngineClient_GetStatsAppID"
addr = 0x74ee0
type = "long long"

[header.args]
