last_change = 2026-09-29T14:51:37.549405Z
addr = 0x74e90
size = 0x11
name = "CEngineClient_FindOrCreateWorldSession"
type = "long long"

[header]
name = "CEngineClient_FindOrCreateWorldSession"
addr = 0x74e90
type = "long long"

[header.args]
