last_change = 2026-09-29T14:51:37.549421Z
addr = 0x7f2d0
size = 0x161
name = "CNetworkGameClientBase_SendStringCmd"
type = "void"

[header]
name = "CNetworkGameClientBase_SendStringCmd"
addr = 0x7f2d0
type = "void"

[header.args]
