last_change = 2026-09-29T14:51:37.549418Z
addr = 0x7e570
size = 0x519
name = "CNetworkGameClientBase_DisconnectGame"
type = "long long"

[header]
name = "CNetworkGameClientBase_DisconnectGame"
addr = 0x7e570
type = "long long"

[header.args]
