last_change = 2026-09-29T14:51:37.549390Z
addr = 0x744e0
size = 0xe
name = "CEngineServer_SetFrameTimeAmnesty"
type = "void"

[header]
name = "CEngineServer_SetFrameTimeAmnesty"
addr = 0x744e0
type = "void"

[header.args]
