last_change = 2026-09-29T14:51:37.549430Z
addr = 0x82690
size = 0x398
name = "CNetworkGameClientBase_ProcessSpawnGroup_ManifestUpdate"
type = "char"

[header]
name = "CNetworkGameClientBase_ProcessSpawnGroup_ManifestUpdate"
addr = 0x82690
type = "char"

[header.args]
