last_change = 2026-09-29T14:51:37.549425Z
addr = 0x815e0
size = 0x1b0
name = "CNetworkGameClientBase_ProcessSetConVar"
type = "char"

[header]
name = "CNetworkGameClientBase_ProcessSetConVar"
addr = 0x815e0
type = "char"

[header.args]
