last_change = 2026-09-29T14:51:37.549446Z
addr = 0x89840
size = 0x17
name = "CNetworkGameClientBase_SendStringCmd2"
type = "long long"

[header]
name = "CNetworkGameClientBase_SendStringCmd2"
addr = 0x89840
type = "long long"

[header.args]
