last_change = 2026-09-29T14:51:37.549452Z
addr = 0x8bc80
size = 0x16e
name = "CNetworkGameClientBase_DeferActivate"
type = "void"

[header]
name = "CNetworkGameClientBase_DeferActivate"
addr = 0x8bc80
type = "void"

[header.args]
