last_change = 2026-09-29T14:51:37.549444Z
addr = 0x89670
size = 0x1c9
name = "CNetworkGameClientBase_ServerCmd"
type = "void"

[header]
name = "CNetworkGameClientBase_ServerCmd"
addr = 0x89670
type = "void"

[header.args]
