last_change = 2026-09-29T14:51:37.549434Z
addr = 0x84e00
size = 0x2e9
name = "CNetworkGameClientBase_ProcessCreateStringTable"
type = "char"

[header]
name = "CNetworkGameClientBase_ProcessCreateStringTable"
addr = 0x84e00
type = "char"

[header.args]
