last_change = 2026-09-29T14:51:37.549448Z
addr = 0x89860
size = 0x249
name = "CNetworkGameClientBase_StartChangeLevel"
type = "long long"

[header]
name = "CNetworkGameClientBase_StartChangeLevel"
addr = 0x89860
type = "long long"

[header.args]
