last_change = 2026-09-29T14:51:37.549481Z
addr = 0x9f9d0
size = 0x4b
name = "CNetworkGameServer_GetPlayerNetworkIDString"
type = "void *"

[header]
name = "CNetworkGameServer_GetPlayerNetworkIDString"
addr = 0x9f9d0
type = "void *"

[header.args]
