last_change = 2026-09-29T14:51:37.549468Z
addr = 0x9e8d0
size = 0x2d6
name = "CNetworkGameServer_ActivateServer"
type = "char"

[header]
name = "CNetworkGameServer_ActivateServer"
addr = 0x9e8d0
type = "char"

[header.args]
