last_change = 2026-09-29T14:51:37.549463Z
addr = 0x9dc30
size = 0x121
name = "CNetworkGameServer_RemoveClientFromGame"
type = "void"

[header]
name = "CNetworkGameServer_RemoveClientFromGame"
addr = 0x9dc30
type = "void"

[header.args]
