last_change = 2026-09-29T14:51:37.549470Z
addr = 0x9ebc0
size = 0x3a3
name = "CNetworkGameServer_PrepareForAssetLoad"
type = "char"

[header]
name = "CNetworkGameServer_PrepareForAssetLoad"
addr = 0x9ebc0
type = "char"

[header.args]
