last_change = 2026-09-29T14:51:37.549455Z
addr = 0x9c500
size = 0xf1
name = "CNetworkGameServer_Init"
type = "long long"

[header]
name = "CNetworkGameServer_Init"
addr = 0x9c500
type = "long long"

[header.args]
