last_change = 2026-09-29T14:51:37.549457Z
addr = 0x9c600
size = 0xd4
name = "CNetworkGameServerBase_SetMaxClients"
type = "double"

[header]
name = "CNetworkGameServerBase_SetMaxClients"
addr = 0x9c600
type = "double"

[header.args]
