last_change = 2026-09-29T14:51:37.549474Z
addr = 0x9f500
size = 0x87
name = "CNetworkGameServer_PreWorldUpdate"
type = "long long"

[header]
name = "CNetworkGameServer_PreWorldUpdate"
addr = 0x9f500
type = "long long"

[header.args]
