last_change = 2026-09-29T14:51:37.549479Z
addr = 0x9f730
size = 0x257
name = "CNetworkGameServer_ServerPostSimulate"
type = "void"

[header]
name = "CNetworkGameServer_ServerPostSimulate"
addr = 0x9f730
type = "void"

[header.args]
