last_change = 2026-09-29T14:51:40.197895Z
addr = 0x9c8d0
size = 0x1cd
name = "CNetworkGameServer_Shutdown"
type = "long long"

[header]
name = "CNetworkGameServer_Shutdown"
addr = 0x9c8d0
type = "long long"

[header.args]
