last_change = 2026-09-29T14:51:37.549571Z
addr = 0xaf2e0
size = 0x23f
name = "CNetworkGameServerBase_CreateFakeClient"
type = "unsigned int *"

[header]
name = "CNetworkGameServerBase_CreateFakeClient"
addr = 0xaf2e0
type = "unsigned int *"

[header.args]
