last_change = 2026-09-29T14:51:37.549554Z
addr = 0xab870
size = 0xb3d
name = "CNetworkGameServerBase_FillKV3ServerInfo"
type = "double"

[header]
name = "CNetworkGameServerBase_FillKV3ServerInfo"
addr = 0xab870
type = "double"

[header.args]
