last_change = 2026-09-29T14:51:40.500590Z
addr = 0xa5d40
size = 0x36b
name = "CNetworkGameServerBase_SendPeerList"
type = "void"

[header]
name = "CNetworkGameServerBase_SendPeerList"
addr = 0xa5d40
type = "void"

[header.args]
