last_change = 2026-09-29T14:51:37.549538Z
addr = 0xa6b50
size = 0x1d2
name = "CNetworkGameServerBase_UserInfoChanged"
type = "long long"

[header]
name = "CNetworkGameServerBase_UserInfoChanged"
addr = 0xa6b50
type = "long long"

[header.args]
