last_change = 2026-09-29T14:51:37.549502Z
addr = 0xa0a50
size = 0x85
name = "CEngineServer_SetFakeClientConVarValue"
type = "long long"

[header]
name = "CEngineServer_SetFakeClientConVarValue"
addr = 0xa0a50
type = "long long"

[header.args]
