last_change = 2026-09-29T14:51:37.549483Z
addr = 0xa0440
size = 0x8
name = "CNetworkGameServerBase_GetPlayerNetworkIDString"
type = "const char *"

[header]
name = "CNetworkGameServerBase_GetPlayerNetworkIDString"
addr = 0xa0440
type = "const char *"

[header.args]
