last_change = 2026-09-29T14:51:37.549520Z
addr = 0xa1390
size = 0xb2
name = "CEngineServer_ClientCommandKeyValues"
type = "void"

[header]
name = "CEngineServer_ClientCommandKeyValues"
addr = 0xa1390
type = "void"

[header.args]
