last_change = 2026-09-29T14:51:37.549508Z
addr = 0xa0c90
size = 0x33
name = "CEngineServer_GetPlayerNetInfo"
type = "long long"

[header]
name = "CEngineServer_GetPlayerNetInfo"
addr = 0xa0c90
type = "long long"

[header.args]
