last_change = 2026-09-29T14:51:37.549547Z
addr = 0xa8190
size = 0x46a
name = "CNetworkGameServerBase_SpawnGroupThink"
type = "long long"

[header]
name = "CNetworkGameServerBase_SpawnGroupThink"
addr = 0xa8190
type = "long long"

[header.args]
