last_change = 2026-09-29T14:51:37.549558Z
addr = 0xad3a0
size = 0x114
name = "CNetworkGameServerBase_SetServerState"
type = "void"

[header]
name = "CNetworkGameServerBase_SetServerState"
addr = 0xad3a0
type = "void"

[header.args]
