last_change = 2026-09-29T14:51:37.549528Z
addr = 0xa1e40
size = 0x49
name = "CEngineServer_IsClientLowViolence"
type = "bool"

[header]
name = "CEngineServer_IsClientLowViolence"
addr = 0xa1e40
type = "bool"

[header.args]
