last_change = 2026-09-29T14:51:37.549510Z
addr = 0xa0cd0
size = 0x5a
name = "CEngineServer_IsUserIDInUse"
type = "long long"

[header]
name = "CEngineServer_IsUserIDInUse"
addr = 0xa0cd0
type = "long long"

[header.args]
