last_change = 2026-09-29T14:51:37.549524Z
addr = 0xa18c0
size = 0x4e
name = "CEngineServer_GetClientSteamID"
type = "long long"

[header]
name = "CEngineServer_GetClientSteamID"
addr = 0xa18c0
type = "long long"

[header.args]
