last_change = 2026-09-29T14:51:37.549514Z
addr = 0xa0d90
size = 0x23d
name = "CEngineServer_ClientCommand"
type = "char"

[header]
name = "CEngineServer_ClientCommand"
addr = 0xa0d90
type = "char"

[header.args]
