last_change = 2026-09-29T14:51:37.549573Z
addr = 0xaf520
size = 0x4f2
name = "CNetworkGameServerBase_Shutdown"
type = "_UNKNOWN **"

[header]
name = "CNetworkGameServerBase_Shutdown"
addr = 0xaf520
type = "_UNKNOWN **"

[header.args]
