last_change = 2026-09-29T14:51:37.549574Z
addr = 0xafa20
size = 0x3f3
name = "CNetworkGameServerBase_BroadcastPrintf"
type = "char"

[header]
name = "CNetworkGameServerBase_BroadcastPrintf"
addr = 0xafa20
type = "char"

[header.args]
