last_change = 2026-09-29T14:51:37.549512Z
addr = 0xa0d70
size = 0x1c
name = "CEngineServer_ServerCommand"
type = "long long"

[header]
name = "CEngineServer_ServerCommand"
addr = 0xa0d70
type = "long long"

[header.args]
