last_change = 2026-09-29T14:51:40.666900Z
addr = 0xaff50
size = 0x3e5
name = "CNetworkGameServerBase_BroadcastMessage"
type = "long long"

[header]
name = "CNetworkGameServerBase_BroadcastMessage"
addr = 0xaff50
type = "long long"

[header.args]
