last_change = 2026-09-29T14:51:37.549499Z
addr = 0xa09f0
size = 0x57
name = "CEngineServer_GetClientConVarValue"
type = "void *"

[header]
name = "CEngineServer_GetClientConVarValue"
addr = 0xa09f0
type = "void *"

[header.args]
