last_change = 2026-09-29T14:51:37.549563Z
addr = 0xadaa0
size = 0xa5
name = "CNetworkGameServerBase_SetGameSpawnGroupMgr"
type = "void"

[header]
name = "CNetworkGameServerBase_SetGameSpawnGroupMgr"
addr = 0xadaa0
type = "void"

[header.args]
