last_change = 2026-09-29T14:51:37.549485Z
addr = 0xa0490
size = 0x17d
name = "CEngineServer_ChangeLevel"
type = "void"

[header]
name = "CEngineServer_ChangeLevel"
addr = 0xa0490
type = "void"

[header.args]
