last_change = 2026-09-29T14:51:37.549526Z
addr = 0xa1970
size = 0x17
name = "CEngineServer_GetServerGlobals"
type = "long long"

[header]
name = "CEngineServer_GetServerGlobals"
addr = 0xa1970
type = "long long"

[header.args]
