last_change = 2026-09-29T14:51:40.418806Z
addr = 0xa12f0
size = 0x4f
name = "CEngineServer_PrecacheGeneric"
type = "long long"

[header]
name = "CEngineServer_PrecacheGeneric"
addr = 0xa12f0
type = "long long"

[header.args]
