last_change = 2026-09-29T14:51:37.549490Z
addr = 0xa0610
size = 0x3d
name = "CEngineServer_IsMapValid"
type = "long long"

[header]
name = "CEngineServer_IsMapValid"
addr = 0xa0610
type = "long long"

[header.args]
