last_change = 2026-09-29T14:51:40.598103Z
addr = 0xad4c0
size = 0x3e8
name = "CNetworkGameServerBase_Init"
type = "long long"

[header]
name = "CNetworkGameServerBase_Init"
addr = 0xad4c0
type = "long long"

[header.args]
