last_change = 2026-09-29T14:51:37.549569Z
addr = 0xaef50
size = 0x38c
name = "CNetworkGameServer_GetFreeClient"
type = "long long"

[header]
name = "CNetworkGameServer_GetFreeClient"
addr = 0xaef50
type = "long long"

[header.args]
