last_change = 2026-09-29T14:51:37.549593Z
addr = 0xb4200
size = 0x228
name = "CNetworkGameServerBase_FinishChangeLevel"
type = "long long"

[header]
name = "CNetworkGameServerBase_FinishChangeLevel"
addr = 0xb4200
type = "long long"

[header.args]
