last_change = 2026-09-29T14:51:37.549628Z
addr = 0xbd890
size = 0x341
name = "CServerSideClient_ExecuteStringCommand"
type = "long long"

[header]
name = "CServerSideClient_ExecuteStringCommand"
addr = 0xbd890
type = "long long"

[header.args]
