last_change = 2026-09-29T14:51:37.549619Z
addr = 0xb93d0
size = 0x4f0
name = "CNetworkServerSpawnGroup_WaitForAssetLoadPrerequisite_GetPrerequisiteStatus"
type = "long long"

[header]
name = "CNetworkServerSpawnGroup_WaitForAssetLoadPrerequisite_GetPrerequisiteStatus"
addr = 0xb93d0
type = "long long"

[header.args]
