last_change = 2026-09-29T14:51:37.549585Z
addr = 0xb38a0
size = 0x9
name = "CNetworkGameServerBase_GetTimescale"
type = "float"

[header]
name = "CNetworkGameServerBase_GetTimescale"
addr = 0xb38a0
type = "float"

[header.args]
