last_change = 2026-09-29T14:51:40.787650Z
addr = 0xb5170
size = 0x34f
name = "CNetworkGameServerBase_ServerSimulate"
type = "void"

[header]
name = "CNetworkGameServerBase_ServerSimulate"
addr = 0xb5170
type = "void"

[header.args]
