last_change = 2026-09-29T14:51:37.549591Z
addr = 0xb3cd0
size = 0x521
name = "CNetworkGameServerBase_StartChangeLevel"
type = "long long"

[header]
name = "CNetworkGameServerBase_StartChangeLevel"
addr = 0xb3cd0
type = "long long"

[header.args]
