last_change = 2026-09-29T14:51:37.549587Z
addr = 0xb38b0
size = 0x2da
name = "CNetworkGameServerBase_OnKickById"
type = "void"

[header]
name = "CNetworkGameServerBase_OnKickById"
addr = 0xb38b0
type = "void"

[header.args]
