last_change = 2026-09-29T14:51:37.549595Z
addr = 0xb4430
size = 0x8
name = "CNetworkGameServerBase_IsChangelevelPending"
type = "long long"

[header]
name = "CNetworkGameServerBase_IsChangelevelPending"
addr = 0xb4430
type = "long long"

[header.args]
