last_change = 2026-09-29T14:51:37.549616Z
addr = 0xb88d0
size = 0x7de
name = "CNetworkServerSpawnGroupCreatePrerequisites_Init"
type = "long long"

[header]
name = "CNetworkServerSpawnGroupCreatePrerequisites_Init"
addr = 0xb88d0
type = "long long"

[header.args]
