last_change = 2026-09-29T14:51:40.761974Z
addr = 0xb4de0
size = 0x1a6
name = "CNetworkGameServerBase_ServerAdvanceTick"
type = "long long"

[header]
name = "CNetworkGameServerBase_ServerAdvanceTick"
addr = 0xb4de0
type = "long long"

[header.args]
