last_change = 2026-09-29T14:51:37.549623Z
addr = 0xbc4d0
size = 0xbb
name = "CServerSideClient_IsHearingClient"
type = "unsigned char"

[header]
name = "CServerSideClient_IsHearingClient"
addr = 0xbc4d0
type = "unsigned char"

[header.args]
