last_change = 2026-09-29T14:51:37.549653Z
addr = 0xca8e0
size = 0xd4
name = "CServerSideClientBase_GetNetworkIDString"
type = "long long"

[header]
name = "CServerSideClientBase_GetNetworkIDString"
addr = 0xca8e0
type = "long long"

[header.args]
