last_change = 2026-09-29T14:51:37.549643Z
addr = 0xc7f50
size = 0x16
name = "CServerSideClientBase_ProcessSpawnGroup_LoadCompleted"
type = "char"

[header]
name = "CServerSideClientBase_ProcessSpawnGroup_LoadCompleted"
addr = 0xc7f50
type = "char"

[header.args]
