last_change = 2026-09-29T14:51:37.549659Z
addr = 0xcac60
size = 0x9
name = "CServerSideClientBase_ProcessSplitPlayerConnect"
type = "char"

[header]
name = "CServerSideClientBase_ProcessSplitPlayerConnect"
addr = 0xcac60
type = "char"

[header.args]
