last_change = 2026-09-29T14:51:37.549635Z
addr = 0xc5210
size = 0x1e6
name = "CServerSideClientBase_Connect"
type = "long long"

[header]
name = "CServerSideClientBase_Connect"
addr = 0xc5210
type = "long long"

[header.args]
