last_change = 2026-09-29T14:51:37.549633Z
addr = 0xc2a20
size = 0x2c9
name = "CServerSideClientBase_ClientPrintf"
type = "char"

[header]
name = "CServerSideClientBase_ClientPrintf"
addr = 0xc2a20
type = "char"

[header.args]
