last_change = 2026-09-29T14:51:37.549647Z
addr = 0xc8370
size = 0x243
name = "CServerSideClientBase_ProcessClientInfo"
type = "char"

[header]
name = "CServerSideClientBase_ProcessClientInfo"
addr = 0xc8370
type = "char"

[header.args]
