last_change = 2026-09-29T14:51:40.910853Z
addr = 0xc5b10
size = 0xc94
name = "CServerSideClientBase_SendServerInfo"
type = "_UNKNOWN **"

[header]
name = "CServerSideClientBase_SendServerInfo"
addr = 0xc5b10
type = "_UNKNOWN **"

[header.args]
