last_change = 2026-09-29T14:51:37.549639Z
addr = 0xc7bf0
size = 0x10b
name = "CServerSideClientBase_ProcessTick"
type = "char"

[header]
name = "CServerSideClientBase_ProcessTick"
addr = 0xc7bf0
type = "char"

[header.args]
