last_change = 2026-09-29T14:51:40.884159Z
addr = 0xc22d0
size = 0x45e
name = "CServerSideClientBase_dtor"
type = "long long"

[header]
name = "CServerSideClientBase_dtor"
addr = 0xc22d0
type = "long long"

[header.args]
