last_change = 2026-09-29T14:51:37.549641Z
addr = 0xc7d00
size = 0x242
name = "CServerSideClientBase_MarkSpawnGroupLoadCompleted"
type = "void"

[header]
name = "CServerSideClientBase_MarkSpawnGroupLoadCompleted"
addr = 0xc7d00
type = "void"

[header.args]
