last_change = 2026-09-29T14:51:37.549651Z
addr = 0xca7f0
size = 0xea
name = "CServerSideClientBase_GetUserIDString"
type = "CUtlString *"

[header]
name = "CServerSideClientBase_GetUserIDString"
addr = 0xca7f0
type = "CUtlString *"

[header.args]
