last_change = 2026-09-29T14:51:37.549649Z
addr = 0xc85d0
size = 0xf6
name = "CServerSideClientBase_ProcessBaselineAck"
type = "char"

[header]
name = "CServerSideClientBase_ProcessBaselineAck"
addr = 0xc85d0
type = "char"

[header.args]
