last_change = 2026-09-29T14:51:37.549645Z
addr = 0xc7f70
size = 0x143
name = "CServerSideClientBase_ProcessStringCmd"
type = "char"

[header]
name = "CServerSideClientBase_ProcessStringCmd"
addr = 0xc7f70
type = "char"

[header.args]
