last_change = 2026-09-29T14:51:40.997471Z
addr = 0xca9c0
size = 0xa0
name = "CServerSideClientBase_GetPlayerInfo"
type = "unsigned int *"

[header]
name = "CServerSideClientBase_GetPlayerInfo"
addr = 0xca9c0
type = "unsigned int *"

[header.args]
