last_change = 2026-09-29T14:51:41.056493Z
addr = 0xf9e20
size = 0x2eb
name = "CSteam3Server_SendUpdatedServerDetails"
type = "long long"

[header]
name = "CSteam3Server_SendUpdatedServerDetails"
addr = 0xf9e20
type = "long long"

[header.args]
