last_change = 2026-09-29T14:51:41.073191Z
addr = 0xfc170
size = 0x118
name = "CBaseSpawnGroup_PrecacheGameSystems"
type = "long long"

[header]
name = "CBaseSpawnGroup_PrecacheGameSystems"
addr = 0xfc170
type = "long long"

[header.args]
