last_change = 2026-09-29T14:51:37.549687Z
addr = 0x106be0
size = 0x47
name = "CNetSupportImpl_Connect"
type = "char"

[header]
name = "CNetSupportImpl_Connect"
addr = 0x106be0
type = "char"

[header.args]
