last_change = 2026-09-29T14:51:41.107080Z
addr = 0x1099d0
size = 0x967
name = "CNetworkStringTableClient_ParseUpdate"
type = "char"

[header]
name = "CNetworkStringTableClient_ParseUpdate"
addr = 0x1099d0
type = "char"

[header.args]
