last_change = 2026-09-29T14:51:37.549705Z
addr = 0x13f930
size = 0x395
name = "CLoopModeLevelLoad_MaybeSwitchToGameLoop"
type = "long long"

[header]
name = "CLoopModeLevelLoad_MaybeSwitchToGameLoop"
addr = 0x13f930
type = "long long"

[header.args]
