last_change = 2026-09-29T14:51:37.549713Z
addr = 0x1b0970
size = 0x72
name = "CGameResourceService_AllocGameResourceManifest"
type = "long long"

[header]
name = "CGameResourceService_AllocGameResourceManifest"
addr = 0x1b0970
type = "long long"

[header.args]
