last_change = 2026-09-29T14:51:37.549719Z
addr = 0x1b0e30
size = 0x216
name = "CGameResourceService_LoadGameResourceManifestNamed"
type = "long long"

[header]
name = "CGameResourceService_LoadGameResourceManifestNamed"
addr = 0x1b0e30
type = "long long"

[header.args]
