last_change = 2026-09-29T14:51:37.549724Z
addr = 0x1b1430
size = 0x1d7
name = "CGameResourceService_LoadGameResourceManifest_IEntityResourceManifest"
type = "long long"

[header]
name = "CGameResourceService_LoadGameResourceManifest_IEntityResourceManifest"
addr = 0x1b1430
type = "long long"

[header.args]
