last_change = 2026-09-29T14:51:37.549732Z
addr = 0x1b1cf0
size = 0x23
name = "CGameResourceService_GetResourceManifestDebugName"
type = "const char *"

[header]
name = "CGameResourceService_GetResourceManifestDebugName"
addr = 0x1b1cf0
type = "const char *"

[header.args]
