last_change = 2026-09-29T14:51:37.549734Z
addr = 0x1b1e20
size = 0x99
name = "CGameResourceService_DescribeContents"
type = "void"

[header]
name = "CGameResourceService_DescribeContents"
addr = 0x1b1e20
type = "void"

[header.args]
