last_change = 2026-09-29T14:51:37.549728Z
addr = 0x1b1940
size = 0x53
name = "CGameResourceService_FreeGameResourceManifest"
type = "void"

[header]
name = "CGameResourceService_FreeGameResourceManifest"
addr = 0x1b1940
type = "void"

[header.args]
