last_change = 2026-09-29T14:51:37.549748Z
addr = 0x1cb430
size = 0x2a6
name = "CMapListService_IsMapValid"
type = "char"

[header]
name = "CMapListService_IsMapValid"
addr = 0x1cb430
type = "char"

[header.args]
