last_change = 2026-09-29T14:51:37.549738Z
addr = 0x1c19f0
size = 0x59b
name = "CInputService_HandleInputEvent"
type = "long long"

[header]
name = "CInputService_HandleInputEvent"
addr = 0x1c19f0
type = "long long"

[header.args]
