last_change = 2026-09-29T14:51:37.549744Z
addr = 0x1c5300
size = 0x492
name = "CInputService_ProcessCommandBuffers"
type = "long long"

[header]
name = "CInputService_ProcessCommandBuffers"
addr = 0x1c5300
type = "long long"

[header.args]
