last_change = 2026-09-29T14:51:41.378233Z
addr = 0x1d2700
size = 0xd84
name = "CNetworkClientService_RegisterEventMapInternal"
type = "long long"

[header]
name = "CNetworkClientService_RegisterEventMapInternal"
addr = 0x1d2700
type = "long long"

[header.args]
