last_change = 2026-09-29T14:51:37.549823Z
addr = 0x1de4e0
size = 0x205
name = "CServerChangelevelState_dtor"
type = "void"

[header]
name = "CServerChangelevelState_dtor"
addr = 0x1de4e0
type = "void"

[header.args]
