last_change = 2026-09-29T14:51:37.549783Z
addr = 0x1d4f60
size = 0x8ea
name = "CNetworkClientService_Init"
type = "long long"

[header]
name = "CNetworkClientService_Init"
addr = 0x1d4f60
type = "long long"

[header.args]
