last_change = 2026-09-29T14:51:41.663977Z
addr = 0x1de450
size = 0x7d
name = "CWaitForInitialSpawnGroupsPrerequisite_GetStatus"
type = "long long"

[header]
name = "CWaitForInitialSpawnGroupsPrerequisite_GetStatus"
addr = 0x1de450
type = "long long"

[header.args]
