last_change = 2026-09-29T14:51:37.549813Z
addr = 0x1d7370
size = 0x3c
name = "CNetworkClientService_IsConnecting"
type = "bool"

[header]
name = "CNetworkClientService_IsConnecting"
addr = 0x1d7370
type = "bool"

[header.args]
