last_change = 2026-09-29T14:51:37.549811Z
addr = 0x1d7260
size = 0x2a
name = "CNetworkClientService_ClockDriftAdjustFrameTime"
type = "double"

[header]
name = "CNetworkClientService_ClockDriftAdjustFrameTime"
addr = 0x1d7260
type = "double"

[header.args]
