last_change = 2026-09-29T14:51:37.549782Z
addr = 0x1d4f20
size = 0x21
name = "CNetworkClientService_OnServerBeginAsyncPostTickWork"
type = "long long"

[header]
name = "CNetworkClientService_OnServerBeginAsyncPostTickWork"
addr = 0x1d4f20
type = "long long"

[header.args]
