last_change = 2026-09-29T14:51:37.549772Z
addr = 0x1d48b0
size = 0x19
name = "CNetworkClientService_OnClientPauseSimulate"
type = "long long"

[header]
name = "CNetworkClientService_OnClientPauseSimulate"
addr = 0x1d48b0
type = "long long"

[header.args]
