last_change = 2026-09-29T14:51:37.549760Z
addr = 0x1d4310
size = 0xc7
name = "CNetworkClientService_AddClientPrerequisites"
type = "long long"

[header]
name = "CNetworkClientService_AddClientPrerequisites"
addr = 0x1d4310
type = "long long"

[header.args]
