last_change = 2026-09-29T14:51:37.549801Z
addr = 0x1d6e50
size = 0x23
name = "CNetworkClientService_IsPutInServer"
type = "bool"

[header]
name = "CNetworkClientService_IsPutInServer"
addr = 0x1d6e50
type = "bool"

[header.args]
