last_change = 2026-09-29T14:51:37.549817Z
addr = 0x1d78f0
size = 0x31
name = "CNetworkClientService_StartChangeLevel"
type = "void"

[header]
name = "CNetworkClientService_StartChangeLevel"
addr = 0x1d78f0
type = "void"

[header.args]
