last_change = 2026-09-29T14:51:37.549798Z
addr = 0x1d6e10
size = 0x18
name = "CNetworkClientService_IsActive"
type = "char"

[header]
name = "CNetworkClientService_IsActive"
addr = 0x1d6e10
type = "char"

[header.args]
