last_change = 2026-09-29T14:51:37.549803Z
addr = 0x1d6ec0
size = 0x1e5
name = "CNetworkClientService_ServerCmd"
type = "void"

[header]
name = "CNetworkClientService_ServerCmd"
addr = 0x1d6ec0
type = "void"

[header.args]
