last_change = 2026-09-29T14:51:37.549778Z
addr = 0x1d4d90
size = 0x15d
name = "CNetworkClientService_OnFrameBoundary"
type = "void"

[header]
name = "CNetworkClientService_OnFrameBoundary"
addr = 0x1d4d90
type = "void"

[header.args]
