last_change = 2026-09-29T14:51:37.549794Z
addr = 0x1d6340
size = 0x2a4
name = "CNetworkClientService_OnStatus"
type = "void"

[header]
name = "CNetworkClientService_OnStatus"
addr = 0x1d6340
type = "void"

[header.args]
