last_change = 2026-09-29T14:51:37.549815Z
addr = 0x1d7820
size = 0x95
name = "CNetworkClientService_ReceivedServerInfo"
type = "long long"

[header]
name = "CNetworkClientService_ReceivedServerInfo"
addr = 0x1d7820
type = "long long"

[header.args]
