last_change = 2026-09-29T14:51:37.549859Z
addr = 0x1e28c0
size = 0x1d4
name = "CNetworkServerService_DisconnectGameNow"
type = "long long"

[header]
name = "CNetworkServerService_DisconnectGameNow"
addr = 0x1e28c0
type = "long long"

[header.args]
