last_change = 2026-09-29T14:51:37.549865Z
addr = 0x1e3230
size = 0x93
name = "CNetworkServerService_GetServerSerializersCRC"
type = "long long"

[header]
name = "CNetworkServerService_GetServerSerializersCRC"
addr = 0x1e3230
type = "long long"

[header.args]
