last_change = 2026-09-29T14:51:37.549869Z
addr = 0x1e3450
size = 0x93
name = "CNetworkServerService_OnKickByIdHLTV"
type = "void"

[header]
name = "CNetworkServerService_OnKickByIdHLTV"
addr = 0x1e3450
type = "void"

[header.args]
