last_change = 2026-09-29T14:51:37.549861Z
addr = 0x1e2b00
size = 0x54
name = "CNetworkServerService_SetFinalSimulationTickThisFrame"
type = "netadr_t *"

[header]
name = "CNetworkServerService_SetFinalSimulationTickThisFrame"
addr = 0x1e2b00
type = "netadr_t *"

[header.args]
