last_change = 2026-09-29T14:51:37.549846Z
addr = 0x1e14e0
size = 0x3e
name = "CNetworkServerService_OnFrameBoundary"
type = "void"

[header]
name = "CNetworkServerService_OnFrameBoundary"
addr = 0x1e14e0
type = "void"

[header.args]
