last_change = 2026-09-29T14:51:41.757048Z
addr = 0x1e0d20
size = 0x2c6
name = "CNetworkServerService_OnServerPostAdvanceTick"
type = "long long"

[header]
name = "CNetworkServerService_OnServerPostAdvanceTick"
addr = 0x1e0d20
type = "long long"

[header.args]
