last_change = 2026-09-29T14:51:37.549851Z
addr = 0x1e1570
size = 0x14e
name = "CNetworkServerService_OnSimpleLoopFrameUpdate"
type = "long long"

[header]
name = "CNetworkServerService_OnSimpleLoopFrameUpdate"
addr = 0x1e1570
type = "long long"

[header.args]
