last_change = 2026-09-29T14:51:41.798915Z
addr = 0x1e1740
size = 0x102d
name = "CNetworkServerService_Init"
type = "long long"

[header]
name = "CNetworkServerService_Init"
addr = 0x1e1740
type = "long long"

[header.args]
