last_change = 2026-09-29T14:51:37.549849Z
addr = 0x1e1560
size = 0x5
name = "CNetworkServerService_OnClientPollNetworking"

[header]
name = "CNetworkServerService_OnClientPollNetworking"
addr = 0x1e1560

[header.args]
