last_change = 2026-09-29T14:51:37.549863Z
addr = 0x1e2bd0
size = 0x78
name = "CNetworkServerService_SetGameLoadStarted"
type = "char"

[header]
name = "CNetworkServerService_SetGameLoadStarted"
addr = 0x1e2bd0
type = "char"

[header.args]
