last_change = 2026-09-29T14:51:37.549833Z
addr = 0x1e0410
size = 0x14
name = "CNetworkServerService_OnServerAdvanceTick"
type = "long long"

[header]
name = "CNetworkServerService_OnServerAdvanceTick"
addr = 0x1e0410
type = "long long"

[header.args]
