last_change = 2026-09-29T14:51:37.549857Z
addr = 0x1e2880
size = 0x15
name = "CNetworkServerService_IsActiveInGame"
type = "char"

[header]
name = "CNetworkServerService_IsActiveInGame"
addr = 0x1e2880
type = "char"

[header.args]
