last_change = 2026-09-29T14:51:37.549876Z
addr = 0x1f4200
size = 0x10e
name = "CSplitScreenService_AddSplitScreenUser"
type = "char"

[header]
name = "CSplitScreenService_AddSplitScreenUser"
addr = 0x1f4200
type = "char"

[header.args]
