last_change = 2026-09-29T14:51:41.873584Z
addr = 0x1f3dc0
size = 0x334
name = "CSplitScreenService_LoadUserConfiguration"
type = "void"

[header]
name = "CSplitScreenService_LoadUserConfiguration"
addr = 0x1f3dc0
type = "void"

[header.args]
