last_change = 2026-09-29T14:51:37.549913Z
addr = 0x213e70
size = 0xf6
name = "CEngineServiceMgr_GetActiveLoop"
type = "void"

[header]
name = "CEngineServiceMgr_GetActiveLoop"
addr = 0x213e70
type = "void"

[header.args]
