last_change = 2026-09-29T14:51:42.076432Z
addr = 0x21cf30
size = 0x283
name = "CLoopTypeBase_GenerateServiceDependencies"
type = "char"

[header]
name = "CLoopTypeBase_GenerateServiceDependencies"
addr = 0x21cf30
type = "char"

[header.args]
