last_change = 2026-09-29T14:51:42.084899Z
addr = 0x21d1c0
size = 0x29c
name = "CLoopTypeBase_GenerateSecondaryDependencies"
type = "char"

[header]
name = "CLoopTypeBase_GenerateSecondaryDependencies"
addr = 0x21d1c0
type = "char"

[header.args]
