last_change = 2026-09-29T14:51:41.976105Z
addr = 0x210fb0
size = 0x142
name = "CEngineServiceMgr_UnregisterLoopMode"
type = "long long"

[header]
name = "CEngineServiceMgr_UnregisterLoopMode"
addr = 0x210fb0
type = "long long"

[header.args]
