last_change = 2026-09-29T14:51:37.549934Z
addr = 0x21f700
size = 0x610
name = "ShowFrameTimeReport"
type = "double"

[header]
name = "ShowFrameTimeReport"
addr = 0x21f700
type = "double"

[header.args]
