last_change = 2026-09-29T14:51:42.002250Z
addr = 0x2120d0
size = 0x12d8
name = "CEngineServiceMgr__MainLoop"
type = "long long"

[header]
name = "CEngineServiceMgr__MainLoop"
addr = 0x2120d0
type = "long long"

[header.args]
