last_change = 2026-09-29T14:51:37.549917Z
addr = 0x2146b0
size = 0x16
name = "CEngineServiceMgr_GetAddonsString"
type = "void *"

[header]
name = "CEngineServiceMgr_GetAddonsString"
addr = 0x2146b0
type = "void *"

[header.args]
