last_change = 2026-09-29T14:51:41.917399Z
addr = 0x2108e0
size = 0xb6
name = "CEngineServiceMgr_Shutdown"
type = "void"

[header]
name = "CEngineServiceMgr_Shutdown"
addr = 0x2108e0
type = "void"

[header.args]
