last_change = 2026-09-29T14:51:41.993159Z
addr = 0x2114f0
size = 0x2a0
name = "CEngineServiceMgr_DeactivateLoop"
type = "long long"

[header]
name = "CEngineServiceMgr_DeactivateLoop"
addr = 0x2114f0
type = "long long"

[header.args]
