last_change = 2026-09-29T14:51:37.549911Z
addr = 0x213a40
size = 0x67
name = "CEngineServiceMgr_OnFrameRenderingFinished"
type = "long long"

[header]
name = "CEngineServiceMgr_OnFrameRenderingFinished"
addr = 0x213a40
type = "long long"

[header.args]
