last_change = 2026-09-29T14:51:37.549919Z
addr = 0x2153b8
size = 0x9
name = "CEngineServiceMgr_RegisterPrerequisite"
type = "long long"

[header]
name = "CEngineServiceMgr_RegisterPrerequisite"
addr = 0x2153b8
type = "long long"

[header.args]
