last_change = 2026-09-29T14:51:37.549909Z
addr = 0x213a20
size = 0x20
name = "CEngineServiceMgr_IsInGameLoop"
type = "char"

[header]
name = "CEngineServiceMgr_IsInGameLoop"
addr = 0x213a20
type = "char"

[header.args]
