last_change = 2026-09-29T14:51:37.549886Z
addr = 0x2109a0
size = 0x8
name = "CEngineServiceMgr_GetEngineWindow"
type = "long long"

[header]
name = "CEngineServiceMgr_GetEngineWindow"
addr = 0x2109a0
type = "long long"

[header.args]
