last_change = 2026-09-29T14:51:37.549954Z
addr = 0x22c000
size = 0x6e6
name = "CLoopTypeClientServer_OutputListeners"
type = "long long"

[header]
name = "CLoopTypeClientServer_OutputListeners"
addr = 0x22c000
type = "long long"

[header.args]
