last_change = 2026-09-29T14:51:37.549948Z
addr = 0x225540
size = 0x13f
name = "CLoopTypeClientServer_DeactivateLoop"
type = "long long"

[header]
name = "CLoopTypeClientServer_DeactivateLoop"
addr = 0x225540
type = "long long"

[header.args]
