last_change = 2026-09-29T14:51:37.549944Z
addr = 0x2250c0
size = 0x25d
name = "CLoopTypeClientServer_AllocateLoopMode"
type = "bool"

[header]
name = "CLoopTypeClientServer_AllocateLoopMode"
addr = 0x2250c0
type = "bool"

[header.args]
