last_change = 2026-09-29T14:51:42.175941Z
addr = 0x2253f0
size = 0x14f
name = "CLoopTypeClientServer_ActivateLoop"
type = "long long"

[header]
name = "CLoopTypeClientServer_ActivateLoop"
addr = 0x2253f0
type = "long long"

[header.args]
