last_change = 2026-09-29T14:51:37.549936Z
addr = 0x221350
size = 0x850
name = "CLoopTypeClientServer_WritePerfStats"
type = "long long"

[header]
name = "CLoopTypeClientServer_WritePerfStats"
addr = 0x221350
type = "long long"

[header.args]
