last_change = 2026-09-29T14:51:42.217615Z
addr = 0x2327d0
size = 0x6f9
name = "CLoopTypeSimple_FrameUpdate"
type = "long long"

[header]
name = "CLoopTypeSimple_FrameUpdate"
addr = 0x2327d0
type = "long long"

[header.args]
