last_change = 2026-09-29T14:51:37.549961Z
addr = 0x23d100
size = 0x14b
name = "CRenderingWorldSession_FindOrCreateWorldSession"
type = "long long"

[header]
name = "CRenderingWorldSession_FindOrCreateWorldSession"
addr = 0x23d100
type = "long long"

[header.args]
