last_change = 2026-09-29T14:51:37.549956Z
addr = 0x232260
size = 0x9c
name = "CLoopTypeSimpleService_OnLoopActivate"
type = "long long"

[header]
name = "CLoopTypeSimpleService_OnLoopActivate"
addr = 0x232260
type = "long long"

[header.args]
